# Generated by Django 3.0.5 on 2020-07-05 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200512_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 6, 0, 4, 20, 218653)),
        ),
    ]
