# Generated by Django 3.0.5 on 2020-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%m/%d/'),
        ),
    ]
